# Generated by Django 3.2.8 on 2021-10-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='material',
            field=models.TextField(default=''),
        ),
    ]
